### ISSUE TITLE
Why not upload to Play store and F-droid?

### ISSUE THREAD

**Issue by RDKRACZ** [Drumber/Kitsune#34]
I found this app by accident, it's better than the official one so I was wondering ^

**Comment by Drumber** [comment]
Hi, since Kitsune is just a hobby project that I work on occasionally, I haven't gotten around to publishing it on the Play store yet.
Also, doing so would require some extra overhead and effort on my part (such as providing support and probably doing some legal stuff), which I don't have the time for at the moment.

But adding it to F-Droid would be an idea I would consider. I haven't really looked into it yet, but I think it should be manageable without requiring too much work.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Drumber/Kitsune/issues/34#issuecomment-1873336303

@Drumber, to my knowledge, [adding it to F-Droid](https://gitlab.com/fdroid/fdroid-website/-/blob/d83681d77b310bdcf712580eca0990922db867fd/_docs/FAQ_-_App_Developers.md#how-do-i-get-my-app-included) shan't require any legal work except https://github.com/Drumber/Kitsune/blob/15bbe739a49423fbef6caf2264a6af0fcc7c0f51/LICENSE#L1-L201, which you've obviously already done.

**Comment by Drumber** [comment]
Hi @RokeJulianLockhart, thanks for bringing this back up. I finally got around to getting the app prepared for publishing on f-droid.

You can follow the progress of the merge request here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14928

I will keep you guys updated as soon as the app is available on f-droid.
