### ISSUE TITLE
App shortcuts - App isn't installed

### ISSUE THREAD

**Issue by ZineeEddine** [Drumber/Kitsune#60]
### Problem description

Problem with the functionality of the Kitsune application shortcuts, when selecting a shortcut from the list or from the home screen an error message appears.
I think there is the problem on real devices
Here is the UI error: 

<p align="left">
  <img src="https://github.com/user-attachments/assets/c8f7e878-4d1d-40b7-af8e-5c4845c16a13" alt="bug-shortcut-app-list-clicked" width="30%" />
  <img src="https://github.com/user-attachments/assets/a0d2aeda-e331-4963-b4d7-c85c1379f250" alt="error_click_shortcut" width="30%" />
</p>

Further you will find the logs of the app since Android 14 - latest version tested on emulator.

Here are links that could help to solve the problem from the official Android Dev documentation and Stack Over Flow:
- Android Dev
https://developer.android.com/develop/ui/views/launch/shortcuts?hl=fr
https://developer.android.com/develop/ui/views/launch/shortcuts/creating-shortcuts?hl=fr
- Stack Over Flow 
https://stackoverflow.com/questions/41134639/app-isn%C2%B4t-installed-error-when-tapping-app-shortcut-in-nougat-7-1-1

### Steps to reproduce

- Long press on the app icon:
Long press the app icon until a context menu appears (usually a menu with several options like "App info", "Delete", and shortcuts).
- Select a shortcut from the menu:
When the context menu appears, choose one of the shortcuts (for example, a quick action or a link to a specific part of the app).
- Error displayed: A notification or window appears saying: "The application is not installed" (or equivalent in another language).

### App version

2.0.1

### Android version

14

### Device information

Emulator basic Android Studio 

### Attachments and Logs

- When selecting a shortcut and depositing it in the home screen
![stacktrace_init_all_shortcut](https://github.com/user-attachments/assets/d5879695-9846-4612-84f7-d4acd981ebfd)
- When selecting a shortcut from the home screen
![stacktrace_library_shortcut](https://github.com/user-attachments/assets/7ec4022d-8e57-4772-9de2-085197e8978f)
![stacktrace_search_shortcut](https://github.com/user-attachments/assets/f5ca11b7-0c67-488e-8b36-5db20bf75cf5)
![stacktrace_settings_shortcut](https://github.com/user-attachments/assets/c3a7cc02-49ae-4b0f-955e-f78842a7e410)
- When selecting from the shortcuts list
![stacktrace-bug-short-cut-from-list](https://github.com/user-attachments/assets/75593990-b4ec-4cc6-a5b3-32613e5bfa51)

### Acknowledgements

- [X] I have searched the open and closed [issues](https://github.com/Drumber/Kitsune/issues?q=is%3Aissue) and this is **NOT** a duplicate.
- [X] I'm using the latest version of the app.
- [X] I have provided all required information.

**Comment by Drumber** [comment]
Hey, thanks for reporting this bug.

Here’s a bit more info about the issue:
The debug build uses a different package name than the production build (`.debug` suffix, see [here](https://github.com/Drumber/Kitsune/blob/master/app/build.gradle.kts#L52)). Since the shortcuts are targeting the package name without the `.debug` suffix (see [here](https://github.com/Drumber/Kitsune/blob/master/app/src/main/res/xml-v25/shortcuts.xml#L10)), the app can't be found, which is why you're seeing that error.

Unfortunately, you can't use placeholders in the shortcuts.xml file, so you would need a separate file for each build flavor, which isn't really maintainable. As a workaround, I’ve implemented a custom gradle task that replaces the target package name in the shortcuts.xml with the actual package name of the current build (see commit 007aae9).
