### ISSUE TITLE
How is it going? 

### ISSUE THREAD

**Issue by MarshMeadow** [Drumber/Kitsune#8]
How is the development..?

**Comment by Drumber** [comment]
I don't have much spare time at the moment, so I can't really work on new features.

As for the current state of development, I made some small changes and bug fixes a while ago, but they are not yet released. I will probably release a new version so that everyone has the latest fixes. However, there will be no major updates in the next weeks.

As soon as I have time (and motivation) to continue working on Kitsune, I have planned to refactor the internal library cache to make updating library entries more responsive. Another big update would be to migrate the UI to Material 3. 

Since this is only a hobby project, I hope you can understand the slow development.
